### ISSUE TITLE
执行./install.sh安装报错   error: 'totalResponse' is not a member of 'tars::ProxyProtocol'

### ISSUE THREAD

**Issue by dpp2009** [TarsCloud/TarsGateway#3]
2020-07-06 17:39:04 ===>install tars.tarsgateway >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 2020-07-06 17:39:04 PARAMS: 118.89.197.217:3000 9abf69f3859f6df4e9a1e747a7d05a28dbfe651a 172.25.0.3 172.25.0.2 3306 root 123456
 2020-07-06 17:39:04 OS: Linux
 2020-07-06 17:39:04 TarsCpp: /usr/local/tars/cpp
 2020-07-06 17:39:04 WebHost: 118.89.197.217:3000
 2020-07-06 17:39:04 Token: 9abf69f3859f6df4e9a1e747a7d05a28dbfe651a
 2020-07-06 17:39:04 Tars-DB: 172.25.0.2
 2020-07-06 17:39:04 ===<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< print envirenment finish.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-------------------------------------------------------------------------------------
CMAKE_SOURCE_DIR:          /data/tars/TarsGateway/TarsGateway
CMAKE_BINARY_DIR:          /data/tars/TarsGateway/TarsGateway/build
PROJECT_SOURCE_DIR:        /data/tars/TarsGateway/TarsGateway
CMAKE_BUILD_TYPE:          Release
PLATFORM:                  linux
TARS2CPP:                  /usr/local/tars/cpp/tools/tars2cpp
TARS_MYSQL:                ON
TARS_HTTP2:                OFF
TARS_SSL:                  OFF
TARS_WEB_HOST:             http://web.tars.com
TARS_TOKEN:
-------------------------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /data/tars/TarsGateway/TarsGateway/build
Scanning dependencies of target tars-GatewayServer
[  7%] Built target tars-GatewayServer
Scanning dependencies of target GatewayServer
[ 14%] Building CXX object src/CMakeFiles/GatewayServer.dir/FlowControlImp.cpp.o
[ 21%] Building CXX object src/CMakeFiles/GatewayServer.dir/FlowControlManager.cpp.o
[ 28%] Building CXX object src/CMakeFiles/GatewayServer.dir/GatewayServer.cpp.o
[ 35%] Building CXX object src/CMakeFiles/GatewayServer.dir/ProxyImp.cpp.o
[ 42%] Building CXX object src/CMakeFiles/GatewayServer.dir/httpproxy/HttpBase.cpp.o
[ 50%] Building CXX object src/CMakeFiles/GatewayServer.dir/httpproxy/HttpCallBack.cpp.o
[ 57%] Building CXX object src/CMakeFiles/GatewayServer.dir/httpproxy/HttpProxy.cpp.o
[ 64%] Building CXX object src/CMakeFiles/GatewayServer.dir/httpproxy/HttpRouter.cpp.o
[ 71%] Building CXX object src/CMakeFiles/GatewayServer.dir/httpproxy/StationManager.cpp.o
[ 78%] Building CXX object src/CMakeFiles/GatewayServer.dir/tupproxy/TupBase.cpp.o
[ 85%] Building CXX object src/CMakeFiles/GatewayServer.dir/tupproxy/TupCallback.cpp.o
[ 92%] Building CXX object src/CMakeFiles/GatewayServer.dir/tupproxy/TupProxyManager.cpp.o
/data/tars/TarsGateway/TarsGateway/src/tupproxy/TupProxyManager.cpp: In constructor 'TupProxyManager::TupProxyManager()':
/data/tars/TarsGateway/TarsGateway/src/tupproxy/TupProxyManager.cpp:9:30: error: 'totalResponse' is not a member of 'tars::ProxyProtocol'
     _prot_tup.responseFunc = ProxyProtocol::totalResponse;
                              ^
make[3]: *** [src/CMakeFiles/GatewayServer.dir/tupproxy/TupProxyManager.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/GatewayServer.dir/all] Error 2
make[1]: *** [src/CMakeFiles/GatewayServer.dir/rule] Error 2
make: *** [GatewayServer] Error 2
 2020-07-06 17:39:54 ===>install GatewayServer server:

{"data":{},"ret_code":500,"err_msg":"系统内部错误"} 2020-07-06 17:39:55 ===>add GatewayServer.conf:

{"data":{},"ret_code":500,"err_msg":"系统内部错误"} 2020-07-06 17:39:55 ====> build_webconf finish!

 2020-07-06 17:39:55 ===>upload GatewayServer server:

 2020-07-06 17:39:55 ====> upload server finish!

 2020-07-06 17:40:00 ===>fetch http://172.25.0.3:8200/monitor/monitor.html to check the gateway in installed ok!

 2020-07-06 17:40:00 test result is:000
 2020-07-06 17:40:00 install fail!

**Comment by shevqko** [comment]
TarsCpp 需要更新到v2.4.4版本。

**Comment by dpp2009** [comment]
这个版本没放出来吧    最新的tag是v2.4.3

**Comment by shevqko** [comment]
放出来了的：  https://github.com/TarsCloud/TarsCpp/releases/tag/v2.4.4

**Comment by dpp2009** [comment]
ok 看到了

**Comment by shevqko** [comment]
恩， 我在ReadMe里面，把对TarsCpp的版本依赖说明也加了一下。
