### ISSUE TITLE
建议tarsnode docker 镜像把glibc 装一下

### ISSUE THREAD

**Issue by YiFabao** [TarsCloud/TarsGateway#7]
安装tarsgateway 并布署到平台运行报下面的错
/usr/local/app/tars/tarsnode/data/tars.GatewayServer/bin/GatewayServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

**Comment by shevqko** [comment]
对libc这些基础库是有依赖，需要服务器环境事先准备好，后续制作docker会把相关依赖一起打包。
