### ISSUE TITLE
error: 'totalResponse' is not a member of 'tars::ProxyProtocol'

### ISSUE THREAD

**Issue by yijie8** [TarsCloud/TarsGateway#8]
/root/TarsGateway/src/tupproxy/TupProxyManager.cpp: In constructor 'TupProxyManager::TupProxyManager()':
/root/TarsGateway/src/tupproxy/TupProxyManager.cpp:9:30: error: 'totalResponse' is not a member of 'tars::ProxyProtocol'
     _prot_tup.responseFunc = ProxyProtocol::totalResponse;
                              ^
make[3]: *** [src/CMakeFiles/GatewayServer.dir/tupproxy/TupProxyManager.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/GatewayServer.dir/all] Error 2
make[1]: *** [src/CMakeFiles/GatewayServer.dir/rule] Error 2
make: *** [GatewayServer] Error 2
 2020-07-27 13:41:56 ===>install GatewayServer server:

**Comment by shevqko** [comment]
TarsCpp 的版本要大于等于 v2.4.5 版本。
